#include "pic.h"

void pic_init(void){
  outb(MASTER_PIC_CMD_STAT, WRITE_ICW1);
  outb(SLAVE_PIC_CMD_STAT, WRITE_ICW1);

  outb(MASTER_PIC_MASK_DATA, WRITE_ICW2_M);
  outb(SLAVE_PIC_MASK_DATA, WRITE_ICW2_S);

  outb(MASTER_PIC_MASK_DATA, WRITE_ICW3_M);
  outb(SLAVE_PIC_MASK_DATA, WRITE_ICW3_S);

  outb(MASTER_PIC_MASK_DATA, WRITE_ICW4_X86MODE);
  outb(SLAVE_PIC_MASK_DATA, WRITE_ICW4_X86MODE);

  //init_irq0
  outb(MASTER_PIC_MASK_DATA, (~PIC_MASK_IRQ0) & (PIC_MASK_IRQ0));

  //init_irq1
  outb(MASTER_PIC_MASK_DATA, (~PIC_MASK_IRQ0) & (~PIC_MASK_IRQ1) & (~PIC_MASK_IRQ2));

  outb(SLAVE_PIC_MASK_DATA, PIC_MASK_IRQA);

}
